### ISSUE TITLE
Issues posted on TEPPP-software/TEPPP are posted here

### ISSUE THREAD

**Issue by samlobe** [Zer0F8th/TEPPP#8]
Just so you know, when I try to submit an issue on the official repo it gives me two options: Bug Report and Documentation Issue. Clicking either one redirects me here to your personal fork. There doesn't seem to be a way to post an issue on the official repo, but I am in fact attempting to install the official repo when I am posting these issues.

Screenshot:
![image](https://user-images.githubusercontent.com/72360861/158487287-e47bd8e4-cd99-40f1-9482-df2b55eb1f99.png)

**Comment by Zer0F8th** [comment]
Thanks I'll look into to!

**Comment by Zer0F8th** [comment]
Okay it should be fixed
